Update actions.yml

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -33,12 +33,18 @@ jobs:
 
         # If we are pointing the PR to master OR have merged on master branch
         if [ "${{ github.event_name }}" = "pull_request" -a "${{ github.base_ref }}" = "master" ] || [ "${{ github.event_name }}" = "push" -a "${{ github.ref }}" = "refs/heads/master" ]; then
-          echo "$package_version" | grep beta && { echo "Version cant contain beta" && exit 1 }
+          echo "$package_version" | grep beta && {
+            echo "Version cant contain beta"
+            exit 1
+          }
         fi
         
         # If we are pointing the PR to beta OR have merged on beta branch
         if [ "${{ github.event_name }}" = "pull_request" -a "${{ github.base_ref }}" = "beta" ] || [ "${{ github.event_name }}" = "push" -a "${{ github.ref }}" = "refs/heads/beta" ]; then
-          echo "$package_version" | grep beta || { echo "Missing beta on version" && exit 1 }
+          echo "$package_version" | grep beta || {
+            echo "Missing beta on version"
+            exit 1
+          }
         fi
 
         cat CHANGELOG.md | grep "$package_version"
